# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-24 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crontabschedule',
            options={'ordering': ['month_of_year', 'day_of_month', 'day_of_week', 'hour', 'minute'], 'verbose_name': '\u5b9a\u65f6\u4efb\u52a1\u65f6\u95f4', 'verbose_name_plural': '\u5b9a\u65f6\u4efb\u52a1\u65f6\u95f4'},
        ),
        migrations.AlterModelOptions(
            name='intervalschedule',
            options={'ordering': ['period', 'every'], 'verbose_name': '\u5faa\u73af\u4efb\u52a1\u65f6\u95f4', 'verbose_name_plural': '\u5faa\u73af\u4efb\u52a1\u65f6\u95f4'},
        ),
        migrations.AlterModelOptions(
            name='periodictask',
            options={'verbose_name': '\u4efb\u52a1\u5217\u8868', 'verbose_name_plural': '\u4efb\u52a1\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='workerstate',
            options={'get_latest_by': 'last_heartbeat', 'ordering': ['-last_heartbeat'], 'verbose_name': '\u4efb\u52a1\u4e3b\u673a', 'verbose_name_plural': '\u4efb\u52a1\u4e3b\u673a'},
        ),
    ]
