# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 08:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u7ec4')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ec4',
                'verbose_name_plural': '\u4e3b\u673a\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('port', models.IntegerField(default=55667, verbose_name='PORT')),
                ('user', models.CharField(max_length=20, verbose_name='\u7ba1\u7406\u7528\u6237')),
                ('pwd', models.CharField(max_length=50, verbose_name='\u7ba1\u7406\u7528\u6237\u5bc6\u7801')),
                ('ips', models.CharField(max_length=200, verbose_name='IP')),
                ('source', models.CharField(max_length=20, verbose_name='\u6765\u6e90')),
                ('status', models.CharField(max_length=50, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='hosts_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.group', verbose_name='\u4e3b\u673a\u7ec4')),
                ('host_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.hosts', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ec4\u5173\u7cfb',
                'verbose_name_plural': '\u4e3b\u673a\u7ec4\u5173\u7cfb',
            },
        ),
    ]
