# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-27 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_task_task_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='source',
            field=models.CharField(blank=True, choices=[('ansible', '\u7cfb\u7edf'), ('custom', '\u81ea\u5b9a\u4e49')], max_length=50, null=True, verbose_name='\u4e3b\u673a\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='source',
            field=models.CharField(blank=True, choices=[('ansible', '\u7cfb\u7edf'), ('custom', '\u81ea\u5b9a\u4e49')], max_length=20, null=True, verbose_name='\u6765\u6e90'),
        ),
    ]
