# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20180527_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u4efb\u52a1', 'verbose_name_plural': '\u4efb\u52a1'},
        ),
        migrations.AlterModelOptions(
            name='task_result',
            options={'verbose_name': '\u4efb\u52a1\u7ed3\u679c', 'verbose_name_plural': '\u4efb\u52a1\u7ed3\u679c'},
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.group', verbose_name='\u4e3b\u673a\u7ec4'),
        ),
    ]
