# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_auto_20180529_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='args',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u53c2\u6570/command'),
        ),
        migrations.AddField(
            model_name='task',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6a21\u5757/playbook'),
        ),
    ]
