# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-30 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_auto_20180530_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('init', '\u4efb\u52a1\u521d\u59cb\u5316'), ('start', '\u5f00\u59cb'), ('running', '\u8fdb\u884c\u4e2d'), ('error', '\u9519\u8bef'), ('done', '\u5df2\u7ed3\u675f')], max_length=15, verbose_name='\u72b6\u6001'),
        ),
    ]
