# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-05 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_auto_20180530_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.hosts', verbose_name='\u4e3b\u673a'),
        ),
    ]
