# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_task_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ys_uid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, verbose_name='UID')),
                ('status', models.CharField(choices=[('using', '\u6b63\u5728\u4f7f\u7528'), ('free', '\u672a\u4f7f\u7528'), ('Disable', '\u4e0d\u53ef\u7528')], max_length=15, verbose_name='\u72b6\u6001')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.hosts', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u592e\u89c6UID',
                'verbose_name_plural': '\u592e\u89c6UID',
            },
        ),
        migrations.AlterField(
            model_name='task_result',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.task', verbose_name='\u4efb\u52a1'),
        ),
    ]
