# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-24 11:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action', '0008_auto_20180605_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ffmpeg_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True, null=True, verbose_name='\u6e90\u6570\u636e')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('status', models.CharField(choices=[('running', '\u8fdb\u884c\u4e2d'), ('done', '\u5df2\u7ed3\u675f')], max_length=15, verbose_name='\u72b6\u6001')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u7528\u6237')),
            ],
            options={
                'verbose_name': 'FFmpeg\u4efb\u52a1',
                'verbose_name_plural': 'FFmpeg\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='task_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6a21\u7248\u540d')),
                ('template', models.TextField(blank=True, null=True, verbose_name='\u6a21\u7248')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u6a21\u7248',
                'verbose_name_plural': '\u4efb\u52a1\u6a21\u7248',
            },
        ),
        migrations.AddField(
            model_name='ffmpeg_task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.task_template', verbose_name='\u6a21\u7248'),
        ),
    ]
