# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0009_auto_20190124_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffmpeg_task',
            name='task',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='celery_task_id'),
        ),
    ]
