# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-01 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0010_ffmpeg_task_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ffmpeg_task',
            options={'verbose_name': '\u77ed\u4efb\u52a1\u4efb\u52a1', 'verbose_name_plural': '\u77ed\u4efb\u52a1\u4efb\u52a1'},
        ),
        migrations.AlterModelOptions(
            name='task_template',
            options={'verbose_name': '\u77ed\u4efb\u52a1\u6a21\u7248', 'verbose_name_plural': '\u77ed\u4efb\u52a1\u6a21\u7248'},
        ),
        migrations.RenameField(
            model_name='ffmpeg_task',
            old_name='task',
            new_name='celery_task_id',
        ),
        migrations.AddField(
            model_name='ffmpeg_task',
            name='log',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4efb\u52a1\u65e5\u5fd7'),
        ),
        migrations.AddField(
            model_name='ffmpeg_task',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4efb\u52a1\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='task_template',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u77ed\u4efb\u52a1\u6a21\u7248\u540d'),
        ),
        migrations.AlterField(
            model_name='task_template',
            name='template',
            field=models.TextField(blank=True, null=True, verbose_name='\u77ed\u4efb\u52a1\u6a21\u7248'),
        ),
    ]
