# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-01 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0011_auto_20190301_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ffmpeg_task',
            new_name='short_task',
        ),
        migrations.RenameModel(
            old_name='task_template',
            new_name='short_task_template',
        ),
    ]
