# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0012_auto_20190301_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_task_template',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u77ed\u4efb\u52a1\u6a21\u7248\u540d'),
        ),
    ]
