# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_auto_20190301_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_task',
            name='command',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8fd0\u884c\u547d\u4ee4'),
        ),
    ]
