# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-06 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0015_auto_20190306_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_task_template',
            name='type',
            field=models.CharField(default='default', max_length=10, null=True, verbose_name='\u77ed\u4efb\u52a1\u6a21\u7248\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='short_task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
