# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0016_auto_20190306_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_task',
            name='log',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4efb\u52a1\u65e5\u5fd7'),
        ),
    ]
